title: Desalegn Gebresilassie
sub-title: xxxxx, ddddd

avatar: "/images/desu.jpg"
description : >-
  A mechanical engineer turned data analyst.
  <a href="https://www.kaggle.com/desalegngeb">View My Kaggle Profile</a> 
theme: jekyll-theme-minimal
