title: Desalegn Gebresilassie
logo: "/images/desu.jpg?raw=true"

description: 
A mechanical engineer by training who is looking to transition into data analysis and science world.
<a href="https://www.kaggle.com/desalegngeb"> View my Kaggle Profile</a>

show_downloads: false
theme: jekyll-theme-minimal
