title: Desalegn Gebresilassie
logo: "/images/desu.jpg?raw=true"
description : >
  A mechanical engineer turned data analyst.
  <a href="https://www.linkedin.com/in/desalegngebresilassie/">View My LinkedIn Profile</a> 
theme: jekyll-theme-minimal
