title: Desalegn Gebresilassie
logo: "/images/desu.jpg?raw=true"


description: >- # this means to ignore newlines until "description" is done
  A showcase of my projects, skills, and experiences.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://yourusername.github.io" # the base hostname & protocol for your site

# Social Links (optional)
email: your-email@example.com
twitter_username: your-twitter-handle
github_username: your-github-username
linkedin: your-linkedin-url

# Theme and appearance
theme: jekyll-theme-minimal # You can change to any other theme you prefer
paginate: 5 # Number of posts per page (if you add a blog section)

# Author info
author:
  name: Your Name
  email: your-email@example.com

# Plugins
plugins:
  - jekyll-feed # For RSS feed
  - jekyll-seo-tag # For SEO improvements

# SEO settings
permalink: pretty
timezone: Your/Timezone

# Exclude from the build (optional)
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock

# Markdown options
markdown: kramdown
highlighter: rouge

