title: Desalegn Gebresilassie
logo: "/images/desu.jpg?raw=true"
description: >- # this means to ignore newlines until "description" is done
 A showcase of my projects, skills, and experiences.
theme: jekyll-theme-minimal # You can change to any other theme you prefer


