title: Desalegn Gebresilassie
logo: "/images/desu.jpg?raw=true"
description: 

<a href="https://www.kaggle.com/desalegngeb"> View my Kaggle Profile</a>

show_downloads: false
theme: jekyll-theme-minimal
